---

- name: Gather OS specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - vars

- include_tasks: install-pkgs.yml
  when: freeipa_client_install_pkgs

- include_tasks: freeipa-client-install.yml
